print('Hi')
print('Hi', 'Mike')
print('Hi', 'Mike', sep=',')
print('Hi', 'Mike', sep=',', end='\n')
print('Hi', 'Mike', sep=',', end='')
print('Hi', 'Mike', sep=',', end='\n')
print('Hi', 'Mike', sep=',', end='.\n')